export interface DistrictCentroid {
  id: string;
  en: string;
  ne: string;
  lat: number;
  lng: number;
}

export const NEPAL_DISTRICTS: DistrictCentroid[] = [
  { id: "achham", en: "Achham", ne: "अछाम", lat: 29.12, lng: 81.3 },
  { id: "baglung", en: "Baglung", ne: "बागलुङ", lat: 28.27, lng: 83.6 },
  { id: "baitadi", en: "Baitadi", ne: "बैतडी", lat: 29.53, lng: 80.52 },
  { id: "bajhang", en: "Bajhang", ne: "बझाङ", lat: 29.58, lng: 81.2 },
  { id: "bajura", en: "Bajura", ne: "बाजुरा", lat: 29.52, lng: 81.55 },
  { id: "banke", en: "Banke (Nepalgunj)", ne: "बाँके (नेपालगन्ज)", lat: 28.15, lng: 81.65 },
  { id: "bara", en: "Bara", ne: "बारा", lat: 27.05, lng: 85.05 },
  { id: "bardiya", en: "Bardiya", ne: "बर्दिया", lat: 28.3, lng: 81.35 },
  { id: "bhaktapur", en: "Bhaktapur", ne: "भक्तपुर", lat: 27.671, lng: 85.4298 },
  { id: "bhojpur", en: "Bhojpur", ne: "भोजपुर", lat: 27.17, lng: 87.05 },
  { id: "chitwan", en: "Chitwan (Bharatpur)", ne: "चितवन (भरतपुर)", lat: 27.5291, lng: 84.3542 },
  { id: "dadeldhura", en: "Dadeldhura", ne: "डडेलधुरा", lat: 29.3, lng: 80.58 },
  { id: "dailekh", en: "Dailekh", ne: "दैलेख", lat: 28.85, lng: 81.72 },
  { id: "dang", en: "Dang (Ghorahi/Tulsipur)", ne: "दाङ", lat: 28.05, lng: 82.3 },
  { id: "darchula", en: "Darchula", ne: "दार्चुला", lat: 29.85, lng: 80.55 },
  { id: "dhading", en: "Dhading", ne: "धादिङ", lat: 27.87, lng: 84.9 },
  { id: "dhankuta", en: "Dhankuta", ne: "धनकुटा", lat: 26.98, lng: 87.33 },
  { id: "dhanusha", en: "Dhanusha (Janakpur)", ne: "धनुषा (जनकपुर)", lat: 26.73, lng: 85.93 },
  { id: "dolakha", en: "Dolakha", ne: "दोलखा", lat: 27.7844, lng: 86.1706 },
  { id: "dolpa", en: "Dolpa", ne: "डोल्पा", lat: 29.05, lng: 82.93 },
  { id: "doti", en: "Doti (Dipayal)", ne: "डोटी", lat: 29.25, lng: 80.93 },
  { id: "gorkha", en: "Gorkha", ne: "गोरखा", lat: 28.2891, lng: 84.6891 },
  { id: "gulmi", en: "Gulmi", ne: "गुल्मी", lat: 28.08, lng: 83.25 },
  { id: "humla", en: "Humla", ne: "हुम्ला", lat: 29.98, lng: 81.82 },
  { id: "ilam", en: "Ilam", ne: "इलाम", lat: 26.9, lng: 87.93 },
  { id: "jajarkot", en: "Jajarkot", ne: "जाजरकोट", lat: 28.7, lng: 82.2 },
  { id: "jhapa", en: "Jhapa (Birtamod)", ne: "झापा", lat: 26.63, lng: 87.98 },
  { id: "jumla", en: "Jumla", ne: "जुम्ला", lat: 29.28, lng: 82.18 },
  { id: "kailali", en: "Kailali (Dhangadhi)", ne: "कैलाली (धनगढी)", lat: 28.7, lng: 80.6 },
  { id: "kalikot", en: "Kalikot", ne: "कालिकोट", lat: 29.23, lng: 81.78 },
  { id: "kanchanpur", en: "Kanchanpur (Mahendranagar)", ne: "कञ्चनपुर", lat: 28.83, lng: 80.33 },
  { id: "kapilvastu", en: "Kapilvastu", ne: "कपिलवस्तु", lat: 27.55, lng: 83.05 },
  { id: "kaski", en: "Kaski (Pokhara)", ne: "कास्की (पोखरा)", lat: 28.2096, lng: 83.9856 },
  { id: "kathmandu", en: "Kathmandu", ne: "काठमाडौं", lat: 27.7172, lng: 85.324 },
  { id: "kavrepalanchok", en: "Kavrepalanchok (Dhulikhel)", ne: "काभ्रेपलाञ्चोक", lat: 27.53, lng: 85.55 },
  { id: "khotang", en: "Khotang", ne: "खोटाङ", lat: 27.2, lng: 86.77 },
  { id: "lalitpur", en: "Lalitpur", ne: "ललितपुर", lat: 27.6588, lng: 85.3247 },
  { id: "lamjung", en: "Lamjung (Besishahar)", ne: "लमजुङ", lat: 28.2415, lng: 84.3871 },
  { id: "mahottari", en: "Mahottari (Jaleshwar)", ne: "महोत्तरी", lat: 26.85, lng: 85.8 },
  { id: "makwanpur", en: "Makwanpur (Hetauda)", ne: "मकवानपुर", lat: 27.43, lng: 85.03 },
  { id: "manang", en: "Manang", ne: "मनाङ", lat: 28.67, lng: 84.02 },
  { id: "morang", en: "Morang (Biratnagar)", ne: "मोरङ (विराटनगर)", lat: 26.65, lng: 87.35 },
  { id: "mugu", en: "Mugu", ne: "मुगु", lat: 29.62, lng: 82.35 },
  { id: "mustang", en: "Mustang (Jomsom)", ne: "मुस्ताङ", lat: 28.8, lng: 83.85 },
  { id: "myagdi", en: "Myagdi (Beni)", ne: "म्याग्दी", lat: 28.35, lng: 83.57 },
  { id: "nawalpur", en: "Nawalpur", ne: "नवलपुर", lat: 27.65, lng: 84.1 },
  { id: "nuwakot", en: "Nuwakot (Bidur)", ne: "नुवाकोट", lat: 27.92, lng: 85.17 },
  { id: "okhaldhunga", en: "Okhaldhunga", ne: "ओखलढुङ्गा", lat: 27.32, lng: 86.5 },
  { id: "palpa", en: "Palpa (Tansen)", ne: "पाल्पा", lat: 27.87, lng: 83.55 },
  { id: "panchthar", en: "Panchthar", ne: "पाँचथर", lat: 27.2, lng: 87.83 },
  { id: "parbat", en: "Parbat (Kusma)", ne: "पर्वत", lat: 28.23, lng: 83.67 },
  { id: "parsa", en: "Parsa (Birgunj)", ne: "पर्सा (वीरगन्ज)", lat: 27.02, lng: 84.88 },
  { id: "pyuthan", en: "Pyuthan", ne: "प्युठान", lat: 28.1, lng: 82.85 },
  { id: "ramechhap", en: "Ramechhap (Manthali)", ne: "रामेछाप", lat: 27.33, lng: 86.08 },
  { id: "rasuwa", en: "Rasuwa (Dhunche)", ne: "रसुवा", lat: 28.1457, lng: 85.2936 },
  { id: "rautahat", en: "Rautahat (Gaur)", ne: "रौतहट", lat: 27.0, lng: 85.3 },
  { id: "rolpa", en: "Rolpa (Liwang)", ne: "रोल्पा", lat: 28.3, lng: 82.63 },
  { id: "rukum_east", en: "Rukum East", ne: "पूर्वी रुकुम", lat: 28.63, lng: 82.7 },
  { id: "rukum_west", en: "Rukum West", ne: "पश्चिम रुकुम", lat: 28.63, lng: 82.48 },
  { id: "rupandehi", en: "Rupandehi (Butwal)", ne: "रुपन्देही (बुटवल)", lat: 27.6, lng: 83.45 },
  { id: "salyan", en: "Salyan", ne: "सल्यान", lat: 28.37, lng: 82.17 },
  { id: "sankhuwasabha", en: "Sankhuwasabha", ne: "संखुवासभा", lat: 27.58, lng: 87.25 },
  { id: "saptari", en: "Saptari (Rajbiraj)", ne: "सप्तरी", lat: 26.6, lng: 86.75 },
  { id: "sarlahi", en: "Sarlahi (Malangwa)", ne: "सर्लाही", lat: 26.98, lng: 85.57 },
  { id: "sindhuli", en: "Sindhuli (Kamalamai)", ne: "सिन्धुली", lat: 27.25, lng: 85.92 },
  { id: "sindhupalchok", en: "Sindhupalchok (Chautara)", ne: "सिन्धुपाल्चोक", lat: 27.9511, lng: 85.6841 },
  { id: "siraha", en: "Siraha", ne: "सिराहा", lat: 26.65, lng: 86.2 },
  { id: "solukhumbu", en: "Solukhumbu (Salleri)", ne: "सोलुखुम्बु", lat: 27.75, lng: 86.7 },
  { id: "sunsari", en: "Sunsari (Dharan/Itahari)", ne: "सुनसरी", lat: 26.65, lng: 87.15 },
  { id: "surkhet", en: "Surkhet (Birendranagar)", ne: "सुर्खेत", lat: 28.6, lng: 81.63 },
  { id: "syangja", en: "Syangja", ne: "स्याङ्जा", lat: 28.08, lng: 83.82 },
  { id: "tanahun", en: "Tanahun (Damauli)", ne: "तनहुँ", lat: 27.97, lng: 84.25 },
  { id: "taplejung", en: "Taplejung", ne: "ताप्लेजुङ", lat: 27.35, lng: 87.67 },
  { id: "terhathum", en: "Terhathum", ne: "तेह्रथुम", lat: 27.15, lng: 87.55 },
  { id: "udayapur", en: "Udayapur (Gaighat)", ne: "उदयपुर", lat: 26.9, lng: 86.52 },
];
